SELECT NOMEM, SUBSTR(NOMEM, 3, 5)
FROM TEMPLE;

SELECT NOMEM, REPLACE(NOMEM, 'A', '0')
FROM TEMPLE;

SELECT INSTR(NOMEM, 'A')
FROM TEMPLE;

SELECT LEFT(NOMEM, 5)
FROM TEMPLE;

SELECT RIGHT(NOMEM, 5)
FROM TEMPLE;

SELECT NOMEM, INSERT(NOMEM, 4, 0, ' HOLA ')
FROM TEMPLE;

SELECT DATE_FORMAT(FECNA, '%D-%M-%Y')
FROM TEMPLE;

SELECT GREATEST(SALAR, EXTEL)
FROM TEMPLE;

SELECT GREATEST(3, 4, 6, 12)
FROM DUAL;

SELECT DATE_ADD(FECIN, INTERVAL 56 YEAR)
FROM TEMPLE;

SELECT DATE_ADD(FECIN, INTERVAL 56 MONTH)
FROM TEMPLE;

SELECT DATE_ADD(FECIN, INTERVAL 56 DAY)
FROM TEMPLE;

SELECT LEAST(3,5,6,67,9)
FROM DUAL;

SELECT LEAST(EXTEL, SALAR)
FROM TEMPLE;

SELECT STRCMP('A', 'E')
FROM DUAL;

SELECT STRCMP('B', 'B')
FROM DUAL;

SELECT STRCMP('E', 'A')
FROM DUAL;

SELECT *
FROM TEMPLE
WHERE (YEAR(CURDATE())-YEAR(FECIN))>50;

SELECT MAX(SALAR), MIN(SALAR), NUMHI
FROM TEMPLE
WHERE NUMHI > 0
GROUP BY NUMHI
HAVING (MAX(SALAR) > 2000 AND COUNT(*) > 1)
ORDER BY NUMHI;

SELECT TDEPTO.NOMDE, TCENTR.NOMCE
FROM TDEPTO, TCENTR
WHERE TDEPTO.NUMCE=TCENTR.NUMCE AND PRESU > 100.000
ORDER BY NOMDE;

SELECT NOMDE, AVG(SALAR)
FROM TEMPLE, TDEPTO
WHERE TEMPLE.NUMDE=TDEPTO.NUMDE
GROUP BY NOMDE
HAVING AVG(SALAR) > (SELECT AVG(SALAR) FROM TEMPLE)
ORDER BY NOMDE;

SELECT NUMDE, 'inferior departamento'
FROM TEMPLE
WHERE SALAR < 2900
UNION
SELECT COUNT(*), 'inferior empleado'
FROM TEMPLE
WHERE SALAR < 2900;

CREATE TABLE OFICINA (

NUMEMPLE INTEGER,
ORDEN INTEGER AUTO_INCREMENT PRIMARY KEY,
DNI INTEGER UNIQUE,
NOMBRE VARCHAR (20) UNIQUE,
PAIS VARCHAR (20) DEFAULT ('ESPAÑA'),
EDAD INTEGER CHECK (EDAD > 18),
COD_OFICINA INTEGER NOT NULL,

FOREIGN KEY (NUMEMPLE) REFERENCES TEMPLE (NUMEM)
);

ALTER TABLE EMPLEADOS
	ADD CONSTRAINT UNO FOREIGN KEY (NUMDE) REFERENCES DEPARTAMENTOS (NUMDE);

ALTER TABLE EMPLEADOS
    ADD CONSTRAINT CASCADA FOREIGN KEY (NUMDE) REFERENCES DEPARTAMENTOS (NUMDE) ON DELETE CASCADE;

