SELECT NOMDE
FROM TDEPTO
WHERE PRESU*1000<(SELECT SUM(SALAR*14)
					FROM TEMPLE
					WHERE NUMDE = TDEPTO.NUMDE)
ORDER BY NOMDE;

/*La misma consulta sin correlación, estaba cerca de acertar*/

SELECT NOMDE
FROM TDEPTO, TEMPLE
WHERE TDEPTO.NUMDE=TEMPLE.NUMDE
GROUP BY NOMDE, PRESU
HAVING PRESU*1000 < SUM(SALAR*14)
ORDER BY NOMDE;