SELECT NOMDE
FROM TDEPTO
WHERE DEPDE IN (SELECT NUMDE 
                FROM TDEPTO
                WHERE PRESU < 50.000);

SELECT D1.NOMDE, D2.NOMDE
FROM TDEPTO D1, TDEPTO D2 /*D1 dependen de los departamentos D2*/
WHERE D2.PRESU < 50 AND D1.DEPDE=D2.NUMDE
ORDER BY 1;

/*Sin condiciones*/

SELECT D1.*, D2.*
FROM TDEPTO D1, TDEPTO D2
WHERE D1.DEPDE=D2.NUMDE
ORDER BY 1;