UPDATE EMPLEADOS
SET EXTEL = EXTEL+1000
WHERE NUMEM IN (SELECT NUMEM
			    FROM TEMPLE, TDEPTO, TCENTR
                WHERE TEMPLE.NUMDE=TDEPTO.NUMDE AND TDEPTO.NUMCE=TCENTR.NUMCE AND DIR LIKE '%ATOCHA%');

SELECT EXTEL
FROM EMPLEADOS
WHERE NUMEM IN (SELECT NUMEM
			    FROM TEMPLE, TDEPTO, TCENTR
                WHERE TEMPLE.NUMDE=TDEPTO.NUMDE AND TDEPTO.NUMCE=TCENTR.NUMCE AND DIR LIKE '%ATOCHA%')