UPDATE EMPLEADOS
JOIN DEPARTAMENTOS ON EMPLEADOS.NUMDE=DEPARTAMENTOS.NUMDE
SET SALAR = SALAR+SALAR*0.0533, COMIS = IFNULL(COMIS,0) + 0.0619*(IFNULL(COMIS, 0))
WHERE NOMDE = 'DIRECCION COMERCIAL';

SELECT NUMDE
FROM DEPARTAMENTOS
WHERE NOMDE = 'DIRECCION COMERCIAL';

SELECT SALAR, COMIS
FROM EMPLEADOS
WHERE NUMDE = 110;