UPDATE EMPLEADOS
SET FECIN = CURDATE()
WHERE NOMEM = 'MORA, VALERIANA';

SELECT FECIN
FROM TEMPLE
WHERE NOMEM = 'MORA, VALERIANA';

/*B)*/

UPDATE EMPLEADOS
SET SALAR = 3100
WHERE NUMEM = 500;

UPDATE EMPLEADOS
SET COMIS = NULL
WHERE NUMEM = 500;

SELECT SALAR, COMIS
FROM EMPLEADOS
WHERE NUMEM = 500;