CREATE TABLE OFICINA (

NUMEMPLE INTEGER,
ORDEN INTEGER AUTO_INCREMENT PRIMARY KEY,
DNI INTEGER UNIQUE NOT NULL,
NOMBRE VARCHAR (20) UNIQUE,
PAIS VARCHAR (20) DEFAULT ('ESPAÑA'),
EDAD INTEGER CHECK (EDAD > 18),
COD_OFICINA INTEGER NOT NULL,

FOREIGN KEY (NUMEMPLE) REFERENCES TEMPLE (NUMEM));

INSERT INTO OFICINA (NUMEMPLE, NOMBRE, COD_OFICINA) VALUES (110, 'SERGI', 3843);
INSERT INTO OFICINA (NUMEMPLE, DNI, NOMBRE, PAIS, EDAD, COD_OFICINA) VALUES (130, 938202, 'Einstein', 'Francia', 50, 4787);

SELECT *
FROM OFICINA;