CREATE TABLE TEMPLENUEVA LIKE TEMPLE; /*Crear una tabla con las columnas de otra sin rellenar, para eso se utiliza el LIKE también*/
CREATE TABLE OFICINA2 LIKE OFICINA;

DESC TEMPLENUEVA;
DESC OFICINA2;

CREATE TABLE TEMPLE2 AS (SELECT *
						 FROM TEMPLE);
DESC TEMPLE2;

CREATE TABLE OFICINA3 AS (SELECT *
						  FROM OFICINA2);
DESC OFICINA3;

CREATE TABLE SALARIOS AS (SELECT NOMEM, SALAR+IFNULL(COMIS, 0) TOTAL
						  FROM TEMPLE);
DESC SALARIOS;

SELECT *
FROM SALARIOS;

CREATE TABLE SALARIOS2 (NUMERO INTEGER, F_NAC DATE) AS (SELECT NOMEM NOMBRE, SALAR+IFNULL(COMIS, 0) TOTAL
														FROM TEMPLE);
SELECT *
FROM SALARIOS2;