ALTER TABLE SALARIOS2 DROP NOMBRE;

SELECT *
FROM SALARIOS2;

CREATE TABLE TDEPTO2 LIKE TDEPTO;
CREATE TABLE TCENTR2 LIKE TCENTR;

RENAME TABLE TEMPLE2 TO EMPLEADOS;
ALTER TABLE TDEPTO2 RENAME TO DEPARTAMENTOS;
ALTER TABLE TCENTR2 RENAME TO CENTROS;

DESC EMPLEADOS;
DESC DEPARTAMENTOS;
DESC CENTROS;

ALTER TABLE EMPLEADOS ADD PRIMARY KEY (NUMEM);
ALTER TABLE DEPARTAMENTOS ADD PRIMARY KEY (NUMDE);
ALTER TABLE CENTROS ADD PRIMARY KEY (NUMCE);

ALTER TABLE EMPLEADOS ADD CONSTRAINT UNO FOREIGN KEY (NUMDE) REFERENCES DEPARTAMENTOS (NUMDE);
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DOS FOREIGN KEY (NUMCE) REFERENCES CENTROS (NUMCE);

ALTER TABLE OFICINA
	ADD DIRECCIÓN VARCHAR (20),
    ADD LOCALIDAD VARCHAR (25);

ALTER TABLE OFICINA
	DROP NOMBRE;

DESC OFICINA;

ALTER TABLE OFICINA
	RENAME COLUMN NUMEMPLE TO IDºEMPLEADO;

ALTER TABLE OFICINA
	ADD FECHA_ALTA DATE;

ALTER TABLE OFICINA
	ADD CONSTRAINT FECHA CHECK (FECHA_ALTA > '2024-1-1');

DELETE FROM EMPLEADOS
WHERE NUMDE=110;

SELECT *
FROM EMPLEADOS;

DESC SALARIOS;

ALTER TABLE SALARIOS
	RENAME COLUMN NOMEM TO Nombre_Empleado,
    RENAME COLUMN TOTAL TO Salario_Total;

SELECT *
FROM SALARIOS;

TRUNCATE TABLE SALARIOS; /*Para borrar todas las filas*/
							/*Para rellenar una tabla con las columnas y filas de otra tabla*/
INSERT INTO SALARIOS
	(SELECT NOMEM, SALAR+IFNULL(COMIS, 0)
     FROM TEMPLE);