CREATE TABLE INFODPT (

NOMBREDPT VARCHAR (20) PRIMARY KEY,
NºEMPLEADOS INTEGER,
SALARIOSDPT INTEGER

);

DESC INFODPT;
DROP TABLE INFODPT;

INSERT INTO INFODPT
	(SELECT NOMDE, COUNT(*), SUM(SALAR)
     FROM TEMPLE, TDEPTO
     WHERE TEMPLE.NUMDE=TDEPTO.NUMDE
     GROUP BY NOMDE);
     
SELECT *
FROM INFODPT;

					/*Para actualizar la tabla cambiando los salarios de los empleados*/
UPDATE EMPLEADOS
SET SALAR = 5000, NUMHI = 5, COMIS = NULL
WHERE NUMEM = 110;