DELETE FROM TEMPLE2
   WHERE SALAR IN (SELECT SALAR
				   FROM TEMPLE E
				   WHERE E.SALAR > (SELECT AVG(E2.SALAR)
									FROM TEMPLE E2
									WHERE E2.NUMDE = E.NUMDE)) AND COMIS IS NULL;
    
    SELECT *
    FROM TEMPLE2;