DROP TABLE TEMPLE2;

CREATE TABLE TBORRA AS (SELECT NUMEM
						FROM TEMPLE
                        WHERE TRUNCATE(DATEDIFF(CURDATE(), FECNA)/365.25, 0) >= 60);

CREATE TABLE TEMPLE2 AS (SELECT *
						 FROM TBORRA);

DELETE FROM TEMPLE
WHERE NUMEM = (SELECT NUMEM
			   FROM TBORRA
               WHERE TEMPLE.NUMEM=TBORRA.NUMEM);

SELECT *
FROM TEMPLE;