UPDATE TEMPLE2
SET SALAR = SALAR + 0.1*SALAR
WHERE NUMDE = 111 AND COMIS IS NULL;

UPDATE TEMPLE2
SET SALAR = SALAR + 0.05*SALAR
WHERE NUMDE = 111 AND COMIS IS NOT NULL;

SELECT COMIS, SALAR
FROM TEMPLE
WHERE NUMDE = 111;