SELECT NUMDE, AVG(SALAR), AVG(NUMHI)
FROM TEMPLE
GROUP BY NUMDE
HAVING AVG(NUMHI)>1 AND NUMDE IN (SELECT NUMDE
                                  FROM TEMPLE
                                  WHERE (TRUNCATE(DATEDIFF(CURDATE(), FECIN)/365.25, 0)) > 10) AND (AVG(NUMHI) >= 1) ;