SELECT NUMDE, COUNT(*) EMPLEADOS, COUNT(DISTINCT EXTEL), COUNT(*)/COUNT(DISTINCT EXTEL)
FROM TEMPLE
GROUP BY NUMDE
HAVING NUMDE IN (SELECT NUMDE
                 FROM TEMPLE
                 WHERE COMIS IS NOT NULL);


/*Otra forma:

SELECT NUMDE, COUNT(*) EMPLEADOS, COUNT(DISTINCT EXTEL), COUNT(*)/COUNT(DISTINCT EXTEL)
FROM TEMPLE
GROUP BY NUMDE
HAVING COUNT(COMIS)>=1; */