SELECT NUMDE, 'Presupuesto Mayor' DEPARTAMENTO
FROM TDEPTO
WHERE PRESU > 110.000
UNION
SELECT NUMDE, 'Suma salario supera 14000€' DEPARTAMENTO
FROM TEMPLE
GROUP BY NUMDE
HAVING SUM(SALAR) > 14000
ORDER BY NUMDE;